### ISSUE TITLE
ruby version

### ISSUE THREAD

**Issue by RyanHedges** [ligerjohn/ligermobile-template#1]
Ruby version is at ruby 2.1 but ruby doesn't have a 2.1 released version. Does this mean 2.1.0? Is the ruby version important  for this project?

**Comment by ligerjohn** [comment]
I've taken to adding in a ```.ruby-version``` and ```.ruby-gemset``` file as well as a Gemfile with cocoapods to all projects that has a LigerMobile iOS app in them. Just because it's often quite useful. I specify the version on ruby as 2.1 as that will load the latest 2.1.x available, so 2.1.5 on my machine. I also don't give cocoapods a version so I can upgrade to the latest fairly easily.

Hopefully nobody is going to need cocoapods while I present, but it's there if someone needs it. I used it when I built the template.

**Comment by RyanHedges** [comment]
Running rbenv so I don't have it understanding what it refers to as "aliases" for its ruby versions. Going to look into that. Thanks for the help @ligerjohn.

**Comment by RyanHedges** [comment]
fwiw: https://github.com/tpope/rbenv-aliases follow directions to install rbenv alias. I did not run `rbenv alias --auto` because I didn't want it to build aliases for all ruby versions.

I ran `rbenv alias 2.1 2.1.5` to build the needed version.
